spring:
  rsocket:
    server:
      mapping-path: "/rsocket"
      transport: "tcp" # gigachad
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ubi
    username: root
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  header: Authorization
  secret: U3dpdGNoIFRlYW0gaGFzIGZpdmUgdGVhbSBtZW1iZXIuIE5hbWVkICdMZWUgSmluc2lrJywgJ01vb24gR2FpbicsICdQYXJrIEp1bmh5dW4nLCAnTGltIEdldW0nLCAnUGFyayBKdXllb25nJy4=
  token-expires-at: 14515200
server:
  port: 8080


cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: ubi-storage
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}