spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  rsocket:
    server:
      mapping-path: "/rsocket"
      transport: "tcp" # gigachad
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ubi
    username: root
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  header: Authorization
  secret: U3dpdGNoIFRlYW0gaGFzIGZpdmUgdGVhbSBtZW1iZXIuIE5hbWVkICdMZWUgSmluc2lrJywgJ01vb24gR2FpbicsICdQYXJrIEp1bmh5dW4nLCAnTGltIEdldW0nLCAnUGFyayBKdXllb25nJy4=
  token-expires-at: 14515200
server:
  port: 20701
  ssl:
    key-store: classpath:jombi.dev.p12
    key-store-password: ${SSL_CERT_KEY}
    key-store-type: pkcs12
  tomcat:
    max-swallow-size: 500000000
    max-http-form-post-size: 500000000


cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: ubi-storage
      access-key: ${AMAZON_ACCESS_KEY}
      secret-key: ${AMAZON_SECRET_KEY}